jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '8'
    - continue-on-error: true
      name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        logout: true
        password: ${{ secrets.PASSWORD }}
        username: ${{ secrets.USERNAME }}
    - continue-on-error: true
      name: Run a one-line script
      run: bash docker-build.sh latest
name: CI
on:
  repository_dispatch:
    types: trigger-ga___main.yml
